MLK-21876-10 gpu: drm: lcdif: fix headfile reference issue
  CC      drivers/gpu/drm/imx/lcdif/lcdif-crtc.o
../drivers/gpu/drm/imx/lcdif/lcdif-crtc.c:26:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 59f9e4438fd4060b92e2f3429e7561ed86d91603
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit 1cd55fcb582b28da1ac94f96068ebe357c107bbb)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>