MGS-4638 [#imx-1373] fix gpu kernel build error with kasan config
If CONFIG_KASAN enabled, gpu kernel driver will throw out the following error:

drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_command.c: In function ‘gckCOMMAND_Commit’:
rivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_command.c:2646:1: error:
the frame size of 2784 bytes is larger than 2048 bytes [-Werror=frame-larger-than=]

Signed-off-by: Xianzhong <xianzhong.li@nxp.com>
(cherry picked from commit d5237ed9bca46858875a9b0ef4134ad477832102)