MLK-21876-6 gpu: drm: dpu: fix build for next-20190524 upgrade
Due to below commit:
b0f986b4b025 ("drm: Remove users of drm_format_info_plane_cpp")

../drivers/gpu/drm/imx/dpu/dpu-plane.c: In function ‘drm_plane_state_to_baseaddr’:
../drivers/gpu/drm/imx/dpu/dpu-plane.c:150:9: error: implicit declaration of function ‘drm_format_plane_cpp’ [-Werror=implicit-function-declaration]
         drm_format_plane_cpp(fb->format->format, 0) * x;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>