MGS-4530-3 [#imx-1314] include dma-direct.h to fix gpu build for L4.19
error: implicit declaration of function ‘dma_to_phys’; did you mean ‘virt_to_phys’? [-Werror=implicit-function-declaration]
     page = phys_to_page(dma_to_phys(&Allocator->os->device->platform->device->dev, mdl_priv->physical));
                         ^
./include/asm-generic/memory_model.h:54:40: note: in definition of macro ‘__pfn_to_page’
 #define __pfn_to_page(pfn) (vmemmap + (pfn))
                                        ^~~
./include/asm-generic/memory_model.h:78:30: note: in expansion of macro ‘PHYS_PFN’
 #define __phys_to_pfn(paddr) PHYS_PFN(paddr)
                              ^~~~~~~~
./arch/arm64/include/asm/memory.h:255:41: note: in expansion of macro ‘__phys_to_pfn’
 #define phys_to_page(phys) (pfn_to_page(__phys_to_pfn(phys)))
                                         ^~~~~~~~~~~~~
gc_hal_kernel_allocator_cma.c:237:12: note: in expansion of macro ‘phys_to_page’
     page = phys_to_page(dma_to_phys(&Allocator->os->device->platform->device->dev, mdl_priv->physical));
            ^~~~~~~~~~~~

Signed-off-by: Xianzhong <xianzhong.li@nxp.com>
(cherry picked from commit d421c76cc1d54086b4435bad1817fa4b7a15df22
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit e4dca01381bf64e6e903219988e231d25a6cce79)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>