LF-1197-1 clk: imx: remove the unused IMX7D_PXP_CLK definition
../drivers/clk/imx/clk-imx7d.c:794:6: error: ‘IMX7D_PXP_CLK’ undeclared (first use in this function); did you mean ‘IMX7D_OCOTP_CLK’?
  794 |  hws[IMX7D_PXP_CLK] = imx_clk_hw_gate4("pxp_clk", "main_axi_root_clk", base + 0x44c0, 0);
      |      ^~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>