MLK-21985-2 vpu: malone: b0: fix build for next 20190607 upgrade
Due to below commit:
7e98b7b542a4 ("media: v4l2: Get rid of ->vidioc_enum_fmt_vid_{cap, out}_mplane")

We met the following build error:
../drivers/mxc/vpu_malone/vpu_b0.c:1721:2: error: unknown field ‘vidioc_enum_fmt_vid_cap_mplane’ specified in initializer
  .vidioc_enum_fmt_vid_cap_mplane = v4l2_ioctl_enum_fmt_vid_cap_mplane,
  ^
../drivers/mxc/vpu_malone/vpu_b0.c:1722:2: error: unknown field ‘vidioc_enum_fmt_vid_out_mplane’ specified in initializer
  .vidioc_enum_fmt_vid_out_mplane = v4l2_ioctl_enum_fmt_vid_out_mplane,

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 937fff61944287a89aa05e0b3df4408309ea429f
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit 7d611236ae63dd2fe67c8a8ad24ba5d0907e0f21)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>