MLK-21876-5 gpu: drm: dpu: fix build for next-20190524 upgrade
In file included from ../drivers/gpu/drm/imx/dpu/dpu-crtc.h:19:0,
                 from ../drivers/gpu/drm/imx/dpu/dpu-crtc.c:29:
../drivers/gpu/drm/imx/dpu/dpu-plane.h:19:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"
                     ^
compilation terminated.
../scripts/Makefile.build:278: recipe for target 'drivers/gpu/drm/imx/dpu/dpu-crtc.o' failed
make[6]: *** [drivers/gpu/drm/imx/dpu/dpu-crtc.o] Error 1
../scripts/Makefile.build:489: recipe for target 'drivers/gpu/drm/imx/dpu' failed
make[5]: *** [drivers/gpu/drm/imx/dpu] Error 2

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit a97e8d033688deb626b490a424af77421963fafc
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit 7e12be0d81216dfc28f03051305be52d72d4c6c0)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>