UBUNTU: [Config] raspi2: Remove upstream mmc modules
BugLink: https://bugs.launchpad.net/bugs/1762835

The Bionic Linux-raspi2 kernel has both the upstream and downstream pi
mmc modules enabled. Running the latest server image users can see
this error in dmesg:

Error: Driver 'sdhost-bcm2835' is already registered, aborting...

Due to this error the pi server image is failing a testcase on the iso
tracker.  It is also not clear to users what mmc modules are in use.

The attached patch removes the upstream mmc modules from the kernel config.

Signed-off-by: Adam Smith <blondesaluki@gmail.com>
[juergh:
 - Adjusted context.
 - Kept CONFIG_MMC_SDHCI_IPROC=m to match rpi-4.19.y.]
Signed-off-by: Juerg Haefliger <juergh@canonical.com>
Acked-by: Connor Kuehl <connor.kuehl@canonical.com>
Acked-by: Paolo Pisati <paolo.pisati@canonical.com>
Acked-by: You-Sheng Yang <vicamo.yang@canonical.com>
Signed-off-by: Khalid Elmously <khalid.elmously@canonical.com>