MGS-5612 [#IMX-2018] fix weston build error
fix weston build error such as:

/opt/fsl-imx-internal-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr/include/HAL/shared/gc_hal_types_shared.h:17:10:
fatal error: gc_hal_version.h: No such file or directory
       17 | #include "gc_hal_version.h"
          |          ^~~~~~~~~~~~~~~~~~
          compilation terminated.

Signed-off-by: Minjie Zhuang <minjie.zhuang@nxp.com>
Signed-off-by: Yong Gan <yong.gan@nxp.com>
(cherry picked from commit 4885c41ad06a495e25d1472c3e305d2b840b7b25
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit c0f88677dcb0104f66509b29fc04e11a6856ff95)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>