imx: mlb: Replace ACCESS_ONCE with READ_ONCE
As per commit 6aa7de059173 ("locking/atomics: COCCINELLE/treewide: Convert
trivial ACCESS_ONCE() patterns to READ_ONCE()/WRITE_ONCE()"), replace
ACCESS_ONCE with READ_ONCE to fix the compilation errors.

drivers/mxc/mlb/mxc_mlb.c: In function ‘mlb_rx_isr’:
drivers/mxc/mlb/mxc_mlb.c:1664:9: error: implicit declaration of function ‘ACCESS_ONCE’; did you mean ‘READ_ONCE’? [-Werror=implicit-function-declaration]
  tail = ACCESS_ONCE(rx_rbuf->tail);
         ^~~~~~~~~~~
         READ_ONCE
  CC      drivers/of/of_mdio.o

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
(cherry picked from commit 98648c7d0e207487ca7ee94499d37f35c68136ef
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit e97ebc2922029f5305f730b371de253b3f94a98f)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>