MGS-4530-2 disable busfreq-imx to fix L4.19 dash build
gc_hal_kernel_platform_imx.c:90:14: fatal error: linux/busfreq-imx.h: No such file or directory
 #    include <linux/busfreq-imx.h>

Signed-off-by: Xianzhong <xianzhong.li@nxp.com>
(cherry picked from commit 40cc89f4fc685bec8be9398ba90ed38c77def497
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit e2b9467c4bc506d15590e964ae6e4c9c41929371)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>