MLK-21876-6 gpu: drm: dpu: fix build for next-20190524 upgrade
Due to below commit:
b0f986b4b025 ("drm: Remove users of drm_format_info_plane_cpp")

../drivers/gpu/drm/imx/dpu/dpu-plane.c: In function ‘drm_plane_state_to_baseaddr’:
../drivers/gpu/drm/imx/dpu/dpu-plane.c:150:9: error: implicit declaration of function ‘drm_format_plane_cpp’ [-Werror=implicit-function-declaration]
         drm_format_plane_cpp(fb->format->format, 0) * x;

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 38b2801e27f5d5a86f8b6fb8d89d558cabd9013a
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit 9055c5fc0570ce5b667a227d22182b44cbbc1a80)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>