MLK-21876-8 gpu: drm: dpu: fix build for next-20190524 upgrade
Due to below commit:
f3e9632cb624 ("drm: Remove users of drm_format_(horz|vert)_chroma_subsampling")

../drivers/gpu/drm/imx/dpu/dpu-plane.c: In function ‘drm_plane_state_to_uvbaseaddr’:
../drivers/gpu/drm/imx/dpu/dpu-plane.c:164:2: error: implicit declaration of function ‘drm_format_horz_chroma_subsampling’ [-Werror=implicit-function-declaration]
  x /= drm_format_horz_chroma_subsampling(fb->format->format);
  ^
../drivers/gpu/drm/imx/dpu/dpu-plane.c:165:2: error: implicit declaration of function ‘drm_format_vert_chroma_subsampling’ [-Werror=implicit-function-declaration]
  y /= drm_format_vert_chroma_subsampling(fb->format->format);
  ^

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 8a7826c80807c362a0d7667919f0ffd4ffe66c22
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit eea99b967c976c245e07d9e839b5f93124d1cd80)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>