MLK-21876-11 gpu: fix build for next-20190524 upgrade
Failed on imx v6_v7 build.

../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:86:17: fatal error: dma.h: No such file or directory
 #include <dma.h>
                 ^
Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 0d03d5163cb23f6b9069fd07d85c40c6a9e589ee
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit 0e5eb8ab01045889f24b929f201f11b47c51b956)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>