MLK-21876-10 gpu: drm: dpu: fix headfile reference issue (part 1)
../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 72559a032dbe71f6ab3cfb96cec88cd60e98ada6
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit d5c3955d445f34595cd54dab6856a82f1645c7a0)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>