MLK-21876-7 gpu: drm: dpu: fix build for next-20190524 upgrade
../drivers/gpu/drm/imx/dpu/dpu-kms.c:23:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 99aa856532e877f794893f300331115e2ab36aa4
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit c67bc4694e403b94f56ca75249840b600728d63e)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>