MLK-21876-10 gpu: drm: ipu: fix headfile reference issue (part2)
../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 672b38b989953eb1e4d14edac9c11b5f75e46031
https://source.codeaurora.org/external/imx/linux-imx)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
(cherry picked from commit 22a4adc7f87b4b2de1cd3be9d94934b835221d89)
Signed-off-by: Shrirang Bagul <shrirang.bagul@canonical.com>