LF-1162-5: clk: imx: imx8mm: add back required clk.h headfile
Otherwise meet below build break:
../drivers/clk/imx/clk-imx8mn.c: In function ‘imx_clk_init_on’:
../drivers/clk/imx/clk-imx8mn.c:306:9: error: implicit declaration of function ‘clk_prepare_enable’ [-Werror=implicit-function-declaration]
  306 |   ret = clk_prepare_enable(clks[array[i]]->clk);
      |         ^~~~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>